### PR TITLE
Update urls in README.md

### PR DESCRIPTION
**Pull request by miguelaferreira**
Replace old klarna urls by the new ones.

### CODE REVIEW

**Comment by j00p34** [comment]
are you aware you're also adding spaces only on some lines?

**Comment by miguelaferreira** [comment]
I'm not adding spaces, I'm removing trailing spaces on some lines. Right?

**Comment by j00p34** [comment]
ok sorry about that. ;-)

**Comment by miguelaferreira** [comment]
Don't be sorry dude. I'm glad you are looking at it. Can you maybe merge it since you're here?

**Pull request merged**
