### PR TITLE
Generate SSH keypair for lifetime of VM

### LINKED ISSUE #124: Generate SSH keys within ACS, specific to a VM, for the lifetime of that VM
The plugin already supports usage of an SSH key-pair generated/stored in ACS (`keypair`).

The plugin should have the following behaviour:

If SSH is needed (SSH Communicator), and `keypair` and `ssh_key` are not specified,
- [Generate a keypair in ACS](https://cloudstack.apache.org/api/apidocs-4.4/domain_admin/createSSHKeyPair.html), and save private key (alongside fwrules id's, etc)
- Use generated keypair name and resulted private keyfile for communication.

For all subsequent communication:
- Use generated keypair name and resulted private keyfile for communication.

On destroy of VM,
- destroy the keypair name in ACS, and remove from disk.

### PR DESCRIPTION
**Pull request by bheuvel**
Fixes #124 

To test this, just leave out both 'ssh_key' and 'keypair'.

But be sure to leave in your bootstrap user in 'ssh_user' (if anything other then 'vagrant' :wink:)

### CODE REVIEW

**Comment by j00p34** [comment]
Hoi Bob,

Zie jij wat er mis is? Of werkt dit alleen met specifieke images?

Hij blijft bij mij hangen op waiting for ssh connection.


---

driver:

  name: vagrant

  provider: cloudstack

  customize:

    host:       betacloud.mccx.schubergphilis.com

    path:       /client/api

    port:       443

    scheme:     https

    api_key:    <%= ENV['CLOUDSTACK_API_KEY'] %>

    secret_key: <%= ENV['CLOUDSTACK_SECRET_KEY'] %>

    template_name:         CentOS 6_5 weekly-w2015-12 V2B29

    service_offering_name: employee-large-ha

    network_name:          vagrant-cloudstack-test1

    zone_name:             BETA-SBP-DC-1

    network_type:          Advanced

    pf_ip_address:    85.222.237.44

    pf_private_port:  22

    pf_open_firewall: false

    pf_trusted_networks:

      -  77.174.245.34/32

#    ssh_key: ~/.ssh/bootstrap.pem

#    ssh_user: bootstrap

    expunge_on_destroy: true


From: Bob
Reply-To: schubergphilis/vagrant-cloudstack
Date: Wednesday 30 September 2015 19:39
To: schubergphilis/vagrant-cloudstack
Subject: [vagrant-cloudstack] Generate SSH keypair for lifetime of VM (#125)


Fixes #124<https://github.com/schubergphilis/vagrant-cloudstack/issues/124>

To test this, just leave out both 'ssh_key' and 'keypair'.

But be sure to leave in your bootstrap user in 'ssh_user' (if anything other then 'vagrant' [:wink:] )

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/schubergphilis/vagrant-cloudstack/pull/125

Commit Summary

  *   Generate SSH keypair for lifetime of VM

File Changes

  *   M README.md<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-0> (2)
  *   M lib/vagrant-cloudstack/action/read_ssh_info.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-1> (7)
  *   M lib/vagrant-cloudstack/action/run_instance.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-2> (35)
  *   M lib/vagrant-cloudstack/action/terminate_instance.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-3> (18)
  *   M locales/en.yml<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-4> (12)

Patch Links:

  *   https://github.com/schubergphilis/vagrant-cloudstack/pull/125.patch
  *   https://github.com/schubergphilis/vagrant-cloudstack/pull/125.diff

**Comment by bheuvel** [comment]
Ja, je moet een 'cis' template hebben. Kijk even op de interne github in mijn vagrant-cloudstack-test repo. In die Vagrantfile staat er één. Degeen die jij hebt (en ik had) ondersteunt die keyname feature niet.

Gr. Bob

Sent from mobile device

On 30 Sep 2015, at 20:34, Timothy van Zadelhoff <notifications@github.com<mailto:notifications@github.com>> wrote:

Hoi Bob,

Zie jij wat er mis is? Of werkt dit alleen met specifieke images?

Hij blijft bij mij hangen op waiting for ssh connection.


---

driver:

name: vagrant

provider: cloudstack

customize:

host: betacloud.mccx.schubergphilis.com<http://betacloud.mccx.schubergphilis.com>

path: /client/api

port: 443

scheme: https

api_key: <%= ENV['CLOUDSTACK_API_KEY'] %>

secret_key: <%= ENV['CLOUDSTACK_SECRET_KEY'] %>

template_name: CentOS 6_5 weekly-w2015-12 V2B29

service_offering_name: employee-large-ha

network_name: vagrant-cloudstack-test1

zone_name: BETA-SBP-DC-1

network_type: Advanced

pf_ip_address: 85.222.237.44

pf_private_port: 22

pf_open_firewall: false

pf_trusted_networks:

- 77.174.245.34/32

# ssh_key: ~/.ssh/bootstrap.pem

# ssh_user: bootstrap

expunge_on_destroy: true


From: Bob
Reply-To: schubergphilis/vagrant-cloudstack
Date: Wednesday 30 September 2015 19:39
To: schubergphilis/vagrant-cloudstack
Subject: [vagrant-cloudstack] Generate SSH keypair for lifetime of VM (#125)


Fixes #124<https://github.com/schubergphilis/vagrant-cloudstack/issues/124>

To test this, just leave out both 'ssh_key' and 'keypair'.

But be sure to leave in your bootstrap user in 'ssh_user' (if anything other then 'vagrant' [:wink:] )

________________________________
You can view, comment on, or merge this pull request online at:

https://github.com/schubergphilis/vagrant-cloudstack/pull/125

Commit Summary

* Generate SSH keypair for lifetime of VM

File Changes

* M README.md<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-0> (2)
* M lib/vagrant-cloudstack/action/read_ssh_info.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-1> (7)
* M lib/vagrant-cloudstack/action/run_instance.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-2> (35)
* M lib/vagrant-cloudstack/action/terminate_instance.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-3> (18)
* M locales/en.yml<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-4> (12)

Patch Links:

* https://github.com/schubergphilis/vagrant-cloudstack/pull/125.patch
* https://github.com/schubergphilis/vagrant-cloudstack/pull/125.diff

**Comment by j00p34** [comment]
Bij mij komt hij er niet door. Vast iets stoms aan mijn kant. Ik loop morgen wel even bij je langs

From: Bob
Reply-To: schubergphilis/vagrant-cloudstack
Date: Wednesday 30 September 2015 20:49
To: schubergphilis/vagrant-cloudstack
Cc: Timothy van Zadelhoff
Subject: Re: [vagrant-cloudstack] Generate SSH keypair for lifetime of VM (#125)

Ja, je moet een 'cis' template hebben. Kijk even op de interne github in mijn vagrant-cloudstack-test repo. In die Vagrantfile staat er één. Degeen die jij hebt (en ik had) ondersteunt die keyname feature niet.

Gr. Bob

Sent from mobile device

On 30 Sep 2015, at 20:34, Timothy van Zadelhoff <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Hoi Bob,

Zie jij wat er mis is? Of werkt dit alleen met specifieke images?

Hij blijft bij mij hangen op waiting for ssh connection.


---

driver:

name: vagrant

provider: cloudstack

customize:

host: betacloud.mccx.schubergphilis.com<http://betacloud.mccx.schubergphilis.com>

path: /client/api

port: 443

scheme: https

api_key: <%= ENV['CLOUDSTACK_API_KEY'] %>

secret_key: <%= ENV['CLOUDSTACK_SECRET_KEY'] %>

template_name: CentOS 6_5 weekly-w2015-12 V2B29

service_offering_name: employee-large-ha

network_name: vagrant-cloudstack-test1

zone_name: BETA-SBP-DC-1

network_type: Advanced

pf_ip_address: 85.222.237.44

pf_private_port: 22

pf_open_firewall: false

pf_trusted_networks:

- 77.174.245.34/32

# ssh_key: ~/.ssh/bootstrap.pem

# ssh_user: bootstrap

expunge_on_destroy: true


From: Bob
Reply-To: schubergphilis/vagrant-cloudstack
Date: Wednesday 30 September 2015 19:39
To: schubergphilis/vagrant-cloudstack
Subject: [vagrant-cloudstack] Generate SSH keypair for lifetime of VM (#125)


Fixes #124<https://github.com/schubergphilis/vagrant-cloudstack/issues/124>

To test this, just leave out both 'ssh_key' and 'keypair'.

But be sure to leave in your bootstrap user in 'ssh_user' (if anything other then 'vagrant' [:wink:] )

________________________________
You can view, comment on, or merge this pull request online at:

https://github.com/schubergphilis/vagrant-cloudstack/pull/125

Commit Summary

* Generate SSH keypair for lifetime of VM

File Changes

* M README.md<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-0> (2)
* M lib/vagrant-cloudstack/action/read_ssh_info.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-1> (7)
* M lib/vagrant-cloudstack/action/run_instance.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-2> (35)
* M lib/vagrant-cloudstack/action/terminate_instance.rb<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-3> (18)
* M locales/en.yml<https://github.com/schubergphilis/vagrant-cloudstack/pull/125/files#diff-4> (12)

Patch Links:

* https://github.com/schubergphilis/vagrant-cloudstack/pull/125.patch
* https://github.com/schubergphilis/vagrant-cloudstack/pull/125.diff

**Comment by j00p34** [comment]
and use a compatible image

**Pull request merged**
