### PR TITLE
Allow assign private ip in config Fixes #52

### LINKED ISSUE #52: Ability to assign a static (private) IP
The CloudStack API call to start a VM allows you to assign an IP address to you VM. The vagrant-cloudstack plugin doesn't expose this capability.

Vagrant's config.vm.network option can be used for it.

### PR DESCRIPTION
**Pull request by j00p34**
This fixes #52 by adding private_ip_address option to config

### CODE REVIEW

**Comment by j00p34** [comment]
@miguelaferreira please review my pull request

**Comment by miguelaferreira** [comment]
@j00p34 doesn't this change also require a change in the underlying fog model?

**Comment by j00p34** [comment]
nope. That was not needed. I've been looking in the wrong direction all the time.
This is tested and works with standard fog. (but you're always welcome to test it yourself)

**Comment by miguelaferreira** [comment]
LGTM

**Pull request merged**
