### PR TITLE
Windows guest (WinRM) support

### PR DESCRIPTION
**Pull request by bheuvel**
This PR solves issue #93 

Upgraded Fog 1.22.0 -> 1.32.0, with one small compatibility fix

Added WinRM "capability"
Retrieve, use and save Cloudstack generated password

After fixing a bug in Vagrant [#5970](https://github.com/mitchellh/vagrant/issues/5970),
this results in successfully provisioning a Windows box in CloudStack.

### CODE REVIEW

**Comment by miguelaferreira** [comment]
What's the "Merge branch 'master' into winrm	fbe2004" commit about?
If you were trying to bring in changes to master, the best way would have been `git pull --rebase master`. This way the changes to master would be bellow your commits, instead as in between.

It's easy to fix, and I can help with that.

**Comment by miguelaferreira** [comment]
@bheuvel,

A lot of comments to go through, some clean up that needs to be done and I (or @j00p34) still need to test this.
However, all-in-all it seems you did a great job with this :+1: 
Thank you for the effort!

**Comment by bheuvel** [comment]
@miguelaferreira sorry about removing all the comments :disappointed: 
But on the upside, I managed to correct the merge-master with a rebase-master (and some more mistakes in between), but thereby apparently removed the comments.
Think that I addressed at least the specific comments though.

**Comment by miguelaferreira** [comment]
@bheuvel strange, the comments usually remain as outdated. But that's now an issue. I'm not traveling everyday, heading back to Amsterdam. I will come find you next week to talk. Thanks :+1:

**Pull request merged**
