### PR TITLE
Static NAT, Port forwarding, Firewall support

### PR DESCRIPTION
**Pull request by atsaki**
Now vagrant-cloudstack can set a port forwarding rule when the virtual machine is deployed.

But there are some limitations.
- only 1 rule can be set
- unable to use in VPC because openfirewall is always true
- can't specify source CIDRs

This patch enables to create Static NAT, Port forwarding, Firewall rules  like Security Groups.
It also delete rules where the instance is destroyed.

### CODE REVIEW

**Comment by atsaki** [comment]
I would like to allow to specify port forwarding IP address directly instead of uuid.
Can you take a look?

**Comment by miguelaferreira** [comment]
Merged into https://github.com/schubergphilis/vagrant-cloudstack

**Comment by atsaki** [comment]
Thanks!

**Comment by miguelaferreira** [comment]
Since we ended up maintaining the original repo, I'll merge this one here too.

**Pull request merged**
