### PR TITLE
Refactoring run/terminate instance

### PR DESCRIPTION
**Pull request by bheuvel**
Mostly moved code to methods and refactored firewall management.

### CODE REVIEW

**Comment by bheuvel** [comment]
Regarding basic networking:

```
Running RSpec tests in folder : basic
Using Vagrant file            : Vagrantfile.basic_networking

Basic Network
  starts Linux VM with security groups
  destroys Linux with security groups

Finished in 1 minute 59.87 seconds (files took 0.12301 seconds to load)
2 examples, 0 failures


Process finished with exit code 0
```

**Comment by bheuvel** [comment]
```
Running RSpec tests in folder : vmlifecycle
Using Vagrant file            : Vagrantfile.advanced_networking

VM Life Cycle
  starts Linux and Windows VM
  destroys Linux and Windows VM

Finished in 3 minutes 16.5 seconds (files took 0.13201 seconds to load)
2 examples, 0 failures


Process finished with exit code 0
```

```
Running RSpec tests in folder : networking
Using Vagrant file            : Vagrantfile.advanced_networking

Networking features
  creates firewall and portwarding rules

Finished in 2 minutes 33.7 seconds (files took 0.11901 seconds to load)
1 example, 0 failures


Process finished with exit code 0
```

**Comment by bheuvel** [comment]
Ping @j00p34 @miguelaferreira 
Can you aprove, or not :wink: ?

Was not sure if to squash most entries or not...

**Comment by miguelaferreira** [comment]
:+1: 

```
➜  mferreira@sbpltk1zkfh04 vagrant-cloudstack (pr/144 ✔ ) bundle exec rake spec   
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
................................................................................................................
Finished in 0.10926 seconds (files took 0.48514 seconds to load)
168 examples, 0 failures

[Coveralls] Outside the CI environment, not sending data.
➜  mferreira@sbpltk1zkfh04 vagrant-cloudstack (pr/144 ✔ ) bundle exec rake functional_tests:all  
Running RSpec tests in folder : vmlifecycle
Using Vagrant file            : Vagrantfile.advanced_networking

VM Life Cycle
  starts Linux and Windows VM
  destroys Linux and Windows VM

Finished in 3 minutes 52 seconds (files took 0.09492 seconds to load)
2 examples, 0 failures

Running RSpec tests in folder : rsync
Using Vagrant file            : Vagrantfile.advanced_networking

VM RSync
Connection to 31.22.84.56 closed.
  does rsync to the VM

Finished in 1 minute 5.89 seconds (files took 0.09307 seconds to load)
1 example, 0 failures

Running RSpec tests in folder : networking
Using Vagrant file            : Vagrantfile.advanced_networking

Networking features
  creates firewall and portwarding rules

Finished in 3 minutes 39.5 seconds (files took 0.12068 seconds to load)
1 example, 0 failures
```

**Pull request merged**
