### PR TITLE
support Rsync Synced Folder

### PR DESCRIPTION
**Pull request by atsaki**
This patch switched the implementation of synced folders from vagrant-cloudstack's sync_folders to vagrant builtin rsync synced folders.

This allows follwing things.
- Install rsync if rsync is not installed in guest os
- vagrant rsync-auto

### CODE REVIEW

**Comment by dduportal** [comment]
Thats a good PR ! Thank you, it'll be usefull with our boot2docker images :)

**Comment by miguelaferreira** [comment]
For reference, I've merged this PR into https://github.com/schubergphilis/vagrant-cloudstack

**Comment by atsaki** [comment]
Thanks!

**Comment by miguelaferreira** [comment]
Since we ended up maintaining the original repo, I'll merge this one here too.

**Pull request merged**
